#!/usr/bin/env bash
# Download large real-world ISO images for local validation.
#
# These images are not committed (too large for git). Tests in
# iso/tests/real_world_large.rs skip silently when the files are absent so
# CI always passes on a fresh checkout. Run this script to enable local runs.
#
# Images come from authoritative third-party sources — never generated by the
# iso crate under test (doer-checker principle).
#
# Requires: python3 (for urllib.request — avoids curl/wget portability issues)
set -euo pipefail

DEST="$(cd "$(dirname "$0")/../iso/tests/data" && pwd)"

fetch() {
  local url="$1" out="$2"
  echo "→ ${out}"
  python3 - "$url" "${DEST}/${out}" <<'EOF'
import sys, urllib.request
urllib.request.urlretrieve(sys.argv[1], sys.argv[2])
print("  done")
EOF
}

# TinyCore Linux 14.0 (23 MB) — GPL-2.0/various open-source
# Source: Tiny Core Linux project, official ibiblio.org mirror
fetch \
  "http://distro.ibiblio.org/tinycorelinux/14.x/x86/release/TinyCore-14.0.iso" \
  "TinyCore-14.0.iso"

# Windows Server 2019 Features on Demand (334 MB) — Microsoft proprietary
# Direct download from Microsoft CDN, no login or form required
# This is the smallest freely downloadable Microsoft ISO that carries UDF NSR02
fetch \
  "https://software-download.microsoft.com/download/pr/17763.1.180914-1434.rs5_release_amd64fre_SERVER-FOD-PACKAGES_OEM_amd64fre_MULTI.iso" \
  "17763.1.180914-1434.rs5_release_amd64fre_SERVER-FOD-PACKAGES_OEM_amd64fre_MULTI.iso"

# Debian 13.5.0 amd64 netinst (755 MB) — DFSG-free
# Source: Official Debian CD image server
fetch \
  "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.5.0-amd64-netinst.iso" \
  "debian-13.5.0-amd64-netinst.iso"

echo ""
echo "Windows XP SP3 VL (x14-74070) must be sourced manually:"
echo "  Search https://archive.org for product ID x14-74070"
echo "  SHA-256: 39430c2b8dd5c21bbd5af9116573f8c574ae896ce31d47280914ef268f01e33f"
echo "  Place in: ${DEST}/zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-74070.iso"
echo ""
echo "Verify checksums with: shasum -a 256 ${DEST}/*.iso"
